### ISSUE TITLE
Logarithm of datapoint

### ISSUE THREAD

**Issue by NightDragon1** [GoshPosh/grafana-meta-queries#100]
Hi!

I would like to calculate the logarithm (ln, base Math.E) of a number. Any chance to get something like this in Meta Queries?

Thanks,
BR,
Rob

**Comment by Gauravshah** [comment]
you should be able to use `Math.log(A['something'])`

**Comment by NightDragon1** [comment]
Thank you!!
Tat solved my issue.

BR,
Rob
