### ISSUE TITLE
Arithmetic is not accurate.  

### ISSUE THREAD

**Issue by gowthamakanthan** [GoshPosh/grafana-meta-queries#101]
Team, 

I am using the Arithmetic operation which highlighted in the screenshot but not getting the accurate value as an output.  Hope am adding in the right manner? 

![Screenshot 2020-05-06 at 10 30 27](https://user-images.githubusercontent.com/4055982/81162164-a41c6200-8f84-11ea-9dda-021390c23110.png) 

![Screenshot 2020-05-06 at 10 30 13](https://user-images.githubusercontent.com/4055982/81162161-a2529e80-8f84-11ea-950d-859d83b6c2af.png)

![Screenshot 2020-05-06 at 10 31 41](https://user-images.githubusercontent.com/4055982/81162278-d29a3d00-8f84-11ea-9234-9f8d915bbcd3.png)

**Comment by Gauravshah** [comment]
105+244+232+243+449 = 1273
looks right calculation.

And if you are looking for the dips I think one of your metric at that instant is a `NaN` 
`(A['CHI CPU'] || 0)+(B['LON CPU'] || 0)....` that should take care

**Comment by gowthamakanthan** [comment]
Gaurav, 
Thanks for the reply. Any idea why the graph is showing weird? The attached example is taken from 30 days and 90 days of data. Not sure why the lines are referring two values on 07-march.

<img width="1642" alt="Screenshot 2020-05-18 at 07 50 23" src="https://user-images.githubusercontent.com/4055982/82182518-4f5ddd00-98dc-11ea-88f6-aec5f618fef6.png">
<img width="1658" alt="Screenshot 2020-05-18 at 07 51 21" src="https://user-images.githubusercontent.com/4055982/82182569-643a7080-98dc-11ea-8b94-8afc9022e157.png">

**Comment by Gauravshah** [comment]
@gowthamakanthan can you try table visualization that should give better idea on what data is being shown

**Comment by gowthamakanthan** [comment]
Okay, I will try the table visualization. Just added the below screenshots for clarity on my issues. I have tried without doing any Arithmetic operation with single CPU value.
<img width="1655" alt="Disabling Total" src="https://user-images.githubusercontent.com/4055982/82193374-37428980-98ed-11ea-892e-9dca63e4f889.png">
<img width="1633" alt="With Total" src="https://user-images.githubusercontent.com/4055982/82193385-3b6ea700-98ed-11ea-9b26-5a5c25f74162.png">
<img width="1652" alt="With-total-2" src="https://user-images.githubusercontent.com/4055982/82193388-3c073d80-98ed-11ea-9cc3-7a2b65317358.png">

**Comment by gowthamakanthan** [comment]
It's working fine after increasing the time interval. :) thank you @Gauravshah
