### ISSUE TITLE
Grafana 6.7.3 + influxdb 1.8 not working ?

### ISSUE THREAD

**Issue by Nibeck1309** [GoshPosh/grafana-meta-queries#102]
Hello,

I want to add this two series, but don't works.

![Screenshot_20200506_133204](https://user-images.githubusercontent.com/11226474/81172707-071af280-8f9f-11ea-84e9-da2e2a24081a.png)

any ideas

**Comment by Gauravshah** [comment]
what kind of visualization is this ? ( I am not aware of min/max working).

Can you try plotting it as table first and then try to move to this visualization ?

**Comment by Nibeck1309** [comment]
Hello,

this is my data in table viszu.
MY problem (I think), it's the data not write at the same time.

Is their a way for correct this ?

![Screenshot_20200507_092920](https://user-images.githubusercontent.com/11226474/81266683-78ad7c00-9045-11ea-9160-42510aebac74.png)

**Comment by Gauravshah** [comment]
You might have to add group by at minute level.
https://community.grafana.com/t/group-by-max-interval-myvar/9772

**Comment by Nibeck1309** [comment]
Hello,

Thanks for your answer.

This resolv my problem.
