### ISSUE TITLE
Grafana v6.7.4

### ISSUE THREAD

**Issue by mubeta06** [GoshPosh/grafana-meta-queries#114]
I am having no luck at all when attempting a simple MetaQuery on Grafana v6.7.4 (8e44bbc5f5) as per the included screen shot. Am I missing something fundamental here?

![image](https://user-images.githubusercontent.com/1686339/96425524-d7f3f700-1247-11eb-8284-7562a840e7ce.png)

**Comment by Gauravshah** [comment]
please refer to readme.
your dashboard is set to "--Mixed--" it should be metaquereis

**Comment by mubeta06** [comment]
🤦 thanks and apologies for wasting your time.
