### ISSUE TITLE
Arithmetic query changes nulls to zeros

### ISSUE THREAD

**Issue by glodkowski** [GoshPosh/grafana-meta-queries#129]
I wanted to use MetaQueries plugin for simple multiplication - to change bytes to bits by multiplying metric values fetched from my datasource.

After setting up targets I noticed that gaps in my graph (when value returned from my datasource is null - meaning that device is not working) have changed to lines at 0.

Fragment of the table of values looks as follows:
| time | metric | metaquery from metric |
|---|---|---|
| 2021-03-12 07:30:00 | 176337943 | 77444892 |
| 2021-03-12 08:00:00 | 243706959 | 95515605 |
| 2021-03-12 08:30:00 | 215001454 | 83802068 |
| 2021-03-12 09:00:00 | 206539989 | 90952909 |
| 2021-03-12 09:30:00 |  | 0 |
| 2021-03-12 10:00:00 |  | 0 |
| 2021-03-12 10:30:00 |  | 0 |
| 2021-03-12 11:00:00 |  | 0 |
| 2021-03-12 11:30:00 |  | 0 |
| 2021-03-12 12:00:00 |  | 0 |
| 2021-03-12 12:30:00 | 290695558 | 92732327 |
| 2021-03-12 13:00:00 | 287216043 | 101118133 |
| 2021-03-12 13:30:00 | 269023669 | 86522832 |
| 2021-03-12 14:00:00 | 330034488 | 94178972 |

And this is how it looks on graph:
* before
![before](https://user-images.githubusercontent.com/73745161/111633240-92872600-87f5-11eb-97b4-98c65e8b0d22.png)
* multiplied
![multiplied](https://user-images.githubusercontent.com/73745161/111633257-96b34380-87f5-11eb-8155-a9350f052ba0.png)

Can this be fixed?

**Comment by glodkowski** [comment]
I just found out that making expression as follows: `A['metric'] || null` does the job, but shouldn't that be the default behaviour?

**Comment by Gauravshah** [comment]
@glodkowski we feel that data should not be manipulated implicitly. As you do have an option to convert it your side.
