### ISSUE TITLE
what do I do wrong with this simple arithmetic test?

### ISSUE THREAD

**Issue by f1-outsourcing** [GoshPosh/grafana-meta-queries#13]
![single-stat](https://user-images.githubusercontent.com/13450219/34782881-46491dee-f62a-11e7-8bc9-b568ae2161cb.png)

**Comment by Gauravshah** [comment]
duplicate of https://github.com/GoshPosh/grafana-meta-queries/issues/10

**Comment by Gauravshah** [comment]
plugin does not work with single stat

**Comment by f1-outsourcing** [comment]
Just a bit curious why is this not working for a singlestat? I don’t know anything of grafana, but I would assume that in general the (result of the) queries section is independent from the graphing.
