### ISSUE TITLE
Does MetaQueries work without aliases?

### ISSUE THREAD

**Issue by CGavrila** [GoshPosh/grafana-meta-queries#130]
Hello. 👋 

I have two queries in a `Mixed` dashboard, one from BigQuery and one from Prometheus. 

What I want to do is have the results divided using MetaQueries, such that I basically get `query A / query B` as a graph.

![image](https://i.imgur.com/6CjxQmo.png)

My best guess at this point is that `A / B` doesn't simply work, so I would need something like `A['cost'] / B['sessions']`, but that doesn't seem to work either. 

Since I have no options of setting aliases for the queries (that I can see), how could I use MetaQueries in this scenario?

**Comment by Gauravshah** [comment]
whats your panel's datasource ?

**Comment by CGavrila** [comment]
@Gauravshah Thank you for your answer.

If you mean the `C` panel, then that should be a MetaQueries panel. I click on `Add query` on the top right, then select `MetaQueries`.

**Comment by Gauravshah** [comment]
can you take a full page screenshot and send it acroos ?

**Comment by CGavrila** [comment]
@Gauravshah Sure, this should be it.

![image](https://i.imgur.com/ihiqge2.png)

**Comment by Gauravshah** [comment]
it says mixed at top. it should be meta-quereis

**Comment by CGavrila** [comment]
@Gauravshah You were absolutely correct. Thank you so much for your help, I tried for hours!

For anyone else struggling with this, my queries now look like this:

![image](https://i.imgur.com/I2E0XuN.png)
