### ISSUE TITLE
Not working on 8.3.1

### ISSUE THREAD

**Issue by yggdrasil-tynor** [GoshPosh/grafana-meta-queries#139]
metaqueries doesn't work on Grafana 8.3.1 even when adding: allow_loading_unsigned_plugins = grafana-meta-queries. Nothing in the logs.

**Comment by acederlund** [comment]
I have the same issue, this is from our log file:
`lvl=warn msg="Skipping loading plugin due to problem with signature" logger=plugin.loader pluginID=goshposh-metaqueries-datasource status=unsigned
`

I did the same with "allow_loading_unsigned_plugins", so I guess it is signed, but there is a problem with the signature.

**Comment by yggdrasil-tynor** [comment]
@acederlund Strange, that it works when downgrading to 8.2.2. So something must have changed in the grafana upstream?

**Comment by jhuebner79** [comment]
This project is dead, isn't it?

**Comment by yggdrasil-tynor** [comment]
Works fine with grafana 8.2.2 :)

**Comment by jhuebner79** [comment]
That doesn't help much - we're not going to downgrade, so: not a real solution :)

**Comment by Antartic0** [comment]
Any update?
I was able to make grafana accept the unsigned plugin but it does not work:

lvl=info msg="Plugin registered" logger=plugin.manager pluginId=goshposh-metaqueries-datasource
lvl=warn msg="Permitting unsigned plugin. This is not recommended" logger=plugin.signature.validator pluginID=goshposh-metaqueries-datasource pluginDir=/var/lib/grafana/plugins/goshposh-metaqueries-datasource

But the plugin is not working with this error:
MetaQueries: Datasource [object Object] was not found

**Comment by yggdrasil-tynor** [comment]
It works with grafana <= 8.2.2. Something upstream broke the integration.

**Comment by Ook3000** [comment]
> It works with grafana <= 8.2.2. Something upstream broke the integration.

But will it be fixed to work afain in Releases > 8.2.2?

**Comment by yggdrasil-tynor** [comment]
> > It works with grafana <= 8.2.2. Something upstream broke the integration.
> 
> But will it be fixed to work afain in Releases > 8.2.2?

If somebody submits a PR :)

**Comment by bene86** [comment]
I tried the fix, but for me it is not properly working. I have to say I'm not an expert in Grafana. I use 8.3.2.
I never had meta-queries propoerly working, I would like to have it for the timeshift functionality.
I tried to set it up according to the docs. Before the fix, as soon as I added any MetaQueries datasource to my panel, it showed only "No data". After the fix, I can add a MetaQueries as second datasource (B) and with "arithmetic" I still see the original data but not the newly calculated data. With "movingAverage" and "TimeShift" I get again No data.
Any ideas, what could be wrong?

**Comment by Gauravshah** [comment]
@bene86 can you send a screenshot of your dashbaord settings, very likely your panel datasource is not set to metaqueires

**Comment by bene86** [comment]
Attached are two screenshots, one for "Arithmetic" one for "Timeshift" (which is what I want)

![image](https://user-images.githubusercontent.com/584526/151675606-b098dc60-0dc4-4951-a184-cbed676d9ad4.png)
![image](https://user-images.githubusercontent.com/584526/151675647-7ce83f13-583c-4c38-9e7c-63ffb90bfed4.png)

**Comment by bene86** [comment]
any usefull hint on the queries? did I set some wrong settings?

**Comment by Gauravshah** [comment]
You need to add Pac or sdf in the metric text box

**Comment by bene86** [comment]
Unfortunately, doesn't help. There is not metric text box for the Arithmetic type and if I type either "Pac" or "sdf" for the TimeShift type, it does not change at all:
![image](https://user-images.githubusercontent.com/584526/152583989-ddd87609-d518-4698-917b-e438b13e81d0.png)

**Comment by appcoders** [comment]
Same here.

**Comment by ShilpaSivanesan** [comment]
Fix for the issue https://github.com/GoshPosh/grafana-meta-queries/pull/128
