### ISSUE TITLE
Signing issue with version 0.0.5 

### ISSUE THREAD

**Issue by SajjadRashid** [GoshPosh/grafana-meta-queries#142]
Hi, is it possible for the author to sign this version, please?

![image](https://user-images.githubusercontent.com/96260772/152406448-85a7f0fc-8cb2-4b2f-be0a-77ab950356d8.png)

**Comment by carlossanchezbailon** [comment]
+1

**Comment by Gauravshah** [comment]
duplicate of https://github.com/GoshPosh/grafana-meta-queries/issues/120

**Comment by ritubajaj89** [comment]
+1

**Comment by SajjadRashid** [comment]
Ok, I only saw that nothing happened for very long time so pushed for new ticket. Will look into the fix
