### ISSUE TITLE
Arithmetic: Broken numbers possible

### ISSUE THREAD

**Issue by benhartwich** [GoshPosh/grafana-meta-queries#150]
Hi,

 I am trying to get broken numbers by using arithmetic like D['in-complete']/C['in-start']. If I use table for visualizing my results I get NaN. Are broken numbers supported?

**Comment by Gauravshah** [comment]
duplicate of https://github.com/GoshPosh/grafana-meta-queries/issues/101

**Comment by benhartwich** [comment]
Sorry, I didn´t get, what might be the right solution. My time interval has already reached the maximum.

**Comment by Gauravshah** [comment]
if your C is NaN I am not sure how do you want to present it on your graph. But lets say you want to plot a 0 it can be done as follows:
`(C['in-start']>0) D['in-complete']/C['in-start'] : 0`
