### ISSUE TITLE
Compatibility with MSSQL

### ISSUE THREAD

**Issue by changochulo** [GoshPosh/grafana-meta-queries#24]
Im running Grafana 5.1 with the native support for Microsoft SQL as a data source.  I installed this plugin but im unable to get any results with the Arithmetic. Do you know if this plugin will work with my current setup at all?

**Comment by Gauravshah** [comment]
it works with grafana 5 and sql, can you send you config as a screenshot ?

**Comment by changochulo** [comment]
Thanks for replying. Im able to add the query using the plugin, I just get no results.
![image](https://user-images.githubusercontent.com/9125405/39060531-78e042a6-4476-11e8-8c13-0bb4e9cd203b.png)

![image](https://user-images.githubusercontent.com/9125405/39060598-a8929508-4476-11e8-867a-e7eccb7747f4.png)

**Comment by changochulo** [comment]
I was reading more into the instructions and changed my datasource from Mixed to MetaQueries, but Im still not seeing any results. I will play around with it some more.

**Comment by Gauravshah** [comment]
glad to know it solved
