### ISSUE TITLE
Using meta-queries without specifying variables?

### ISSUE THREAD

**Issue by sam5558** [GoshPosh/grafana-meta-queries#27]
I'm using grafana & [grafana-rrd-server](https://github.com/doublemarket/grafana-rrd-server) to display some rrd metrics.
I'm interested in using meta-queries to do some arithmetic calculations - but it seems that i need to write my queries in this form : `A['variable1'] + B['variable2']`.

The problem that i have is with grafana-rrd-server, as it's displaying metrics on the fly, without using variable1. 
So i'm wondering if it's possible to use the meta-queries without specifying the variable metric like for eg. using a wildcard `A['*'] + B['*']` , or even without specifying anything aside from the 2 rows for metrics `A + B`. 

any help is appreciated.
Thanks

**Comment by Gauravshah** [comment]
I am not sure of how grafana-rdd-server works. Can you post an example of
your dashboard with ‘*’ ?

**Comment by sam5558** [comment]
Well, i found another way to display the metrics i want & do the caclulations i want directly from my datasource. 
So i'll close this issue.
Thanks anyway @Gauravshah .
