### ISSUE TITLE
Meta-query with Prometheus Data source possible?

### ISSUE THREAD

**Issue by johnnyb2good** [GoshPosh/grafana-meta-queries#28]
Hi there.  Similar to the question from [https://github.com/GoshPosh/grafana-meta-queries/issues/27](url),
is there a way to reference query lines from a Prometheus data sourced query without using a variable for the meta-query?  There does not appear to be a way to assign Prometheus queries to a variable in Grafana.

See screenshot for example.  The metaquery does not reference C or D properly regardless of format tested, examples of which were C['\*'], C[], C, C[\*], C['(prometheus)'], etc.

Thanks,

John

![image](https://user-images.githubusercontent.com/20143009/40341078-0569c34e-5d51-11e8-85a7-88f2598937bf.png)

**Comment by Gauravshah** [comment]
@johnnyb2good you need to set panel data source to "metaquery".
I do not know of a way to query without the reference. I have not used prometheus with grafana so unsure how would it work. But I think if you show the graph, there must be some legend that grafana gives probably use the same ? A['grafana_name'] something like that

**Comment by johnnyb2good** [comment]
That works, thanks!

- Panel data source needed to be metaquery
- The prometheus queries have to come before the metaquery
- The "Legend format" name is what needs to be used in the metaquery reference.  In the example above, like: C['total completed count']
- Recreating the above pictured panel with the above considerations got it working as expected.

Thanks again!

John
