### ISSUE TITLE
Graphite references are not working

### ISSUE THREAD

**Issue by benmathews** [GoshPosh/grafana-meta-queries#32]
When trying to reference a graphite metric, I get JS errors in the console log and no value for the Meta metric.

```
datasource.js:240 ReferenceError: C is not defined
    at eval (eval at <anonymous> (datasource.js:NaN), <anonymous>:3:1)
    at eval (datasource.js:237)
    at Array.forEach (<anonymous>)
    at eval (datasource.js:233)
    at u (angular.js:17051)
    at angular.js:17095
    at h.$digest (angular.js:18233)
    at h.$apply (angular.js:18531)
    at angular.js:18832
    at i (angular.js:6362)
    at angular.js:6642
```

I believe that the problem is that in my prometheus sample, a legendFormat key is created. This doesn't exist on the graphite metric
![screenshot from 2018-08-24 14-55-08](https://user-images.githubusercontent.com/446380/44607524-fa943d80-a7ad-11e8-97ea-71f76f378ba6.png)

**Comment by Gauravshah** [comment]
can you confirm if its related to https://github.com/grafana/grafana/issues/11461 ?
we have seen graphite not working

**Comment by benmathews** [comment]
Garbage, it looks like that is the problem. I see the same `Panel request canceled` error. I was looking forward to using this.
