### ISSUE TITLE
Adding additional CloudWatch query causes Arithmetic MetaQuery to show "clipped" results

### ISSUE THREAD

**Issue by matthicks05** [GoshPosh/grafana-meta-queries#36]
I'm successfully using MetaQueries (great feature!) to calculate some DynamoDB cloudwatch metrics by taking a sum of the write_capacity metric and dividing it by 60 using an Arithmetic query.

![image](https://user-images.githubusercontent.com/7862124/45958427-08bbc080-bfdd-11e8-8c75-c7d1361cbb0b.png)

Once I add another CloudWatch query, in this case the "Provisioned Write Capacity", which is essentially a threshold I want to compare the Arithmetic query to, the MetaQuery becomes "clipped".

![image](https://user-images.githubusercontent.com/7862124/45958574-66500d00-bfdd-11e8-898f-5c814930df9a.png)

Once I remove Query C, the MetaQuery functions normally once again.

Using (latest) version 0.0.1 of MetaQuery plugin.
Using Grafana v5.0.0

**Comment by Gauravshah** [comment]
Can you plot a table instead of graph with same configuration ? That will
give us some idea as to what are the datapoints
