### ISSUE TITLE
Data source creation error

### ISSUE THREAD

**Issue by ggajanan** [GoshPosh/grafana-meta-queries#41]
I installed this plugin on latest grafana 5.3.0 version. While trying to create the datasource, it's failing with following error when clicked 'Save & Test' button

```
Meta plugin failed
Error: Fetch error: 404 Not Found Instantiating http://localhost:3000/public/app/plugins/datasource/goshposh-metaqueries-datasource/module Loading app/plugins/datasource/goshposh-metaqueries-datasource/module
```

![image](https://user-images.githubusercontent.com/23700404/46832419-f62ede80-cd73-11e8-9ff1-64a1d9d3f874.png)

**Comment by Gauravshah** [comment]
@ShilpaSivanesan I do not see any breaking changes from grafana side. Anything simple that we can do to fix it ?

**Comment by ShilpaSivanesan** [comment]
@ggajanan I tried installing the plugin on grafana versions 5.30 and 5.3.2. I don't see any error with adding datasource

<img width="976" alt="screen shot 2018-10-28 at 11 13 35 pm" src="https://user-images.githubusercontent.com/34906268/47632443-57420a80-db07-11e8-924d-6efa43edb0e5.png">

**Comment by Gauravshah** [comment]
@ggajanan did you try latest code from master ?
