### ISSUE TITLE
Cannot install on latest version

### ISSUE THREAD

**Issue by Dylantje** [GoshPosh/grafana-meta-queries#44]
Dear i try to install this plugin to the latest grafana version only i get error:
`i@raspberrypi:~ $ grafana-cli plugins install goshposh-metaqueries-datasource
installing goshposh-metaqueries-datasource @ 0.0.1
from url: https://grafana.com/api/plugins/goshposh-metaqueries-datasource/versions/0.0.1/download
into: /var/lib/grafana/plugins

Failed downloading. Will retry once.
Failed downloading. Will retry once.

Error: ✗ Corrupt http response from source. Please try again.

NAME:
   Grafana cli plugins install - install <plugin id> <plugin version (optional)>

USAGE:
   Grafana cli plugins install [arguments...]
`
So i hope u have a solution...

**Comment by Gauravshah** [comment]
@Dylantje do you still face issue with version 0.0.2 ?
