### ISSUE TITLE
Problems with arithmetic queries

### ISSUE THREAD

**Issue by TheRealKerni** [GoshPosh/grafana-meta-queries#45]
Hi there,

first of all thanks so much for this plugin. It really helps a lot getting around limitations when using InfluxDB in my case!

I am trying to create a combined chart (energy consumption) of multiple items. In addition I have the value of the total energy consumption and would like to provide a "Rest" item using MetaQueries.

Basically something like: `A['Total']-B['PVGeneration']-C['Heating']-D['WarmWater']-E['WashingMachine']`

My problem is that the values for `E['WashingMachine']`have been added later and more items like that will be added over time. The above formula only works and will result in data being shown if there is at least one data point in the visible timeframe, otherwise the item will not be shown.

Instead it should treat the item as `0` values. But I wasn't able to get this working.

This is what I tried instead:

```
A['Total']-B['PVGeneration']-C['Heating']-D['WarmWater']-(E['WashingMachine']>0?E['WashingMachine']:0)
A['Total']-B['PVGeneration']-C['Heating']-D['WarmWater']-((E['WashingMachine'])?E['WashingMachine']:0)
```

Any suggestions on how to get this done?

P.S.: As a side note: I'd love to have the input field being much wider so I can see the actual long formulas and don't have to copy them to a text editor all the time :)

**Comment by zegerhoogeboom** [comment]
I believe `E['WashingMachine']` will already fail due to `E` being undefined. From the top of my head, something like `{your query} - (E && E['WashingMachine'] ? E['WashingMachine'] : 0)` might work.

**Comment by TheRealKerni** [comment]
Perfect, thank you! Why didn't I think of this :)

**Comment by Gauravshah** [comment]
thanks @zegerhoogeboom 
@TheRealKerni Can you please raise a different issue for textbox size, will try to add it for next release

**Comment by TheRealKerni** [comment]
Done at https://github.com/GoshPosh/grafana-meta-queries/issues/46
