### ISSUE TITLE
Grafana option "Min time interval" not available

### ISSUE THREAD

**Issue by TheRealKerni** [GoshPosh/grafana-meta-queries#47]
Hi,

when using MetaQueries with a set of InfluxDB (or ElasticSearch according to the Grafana documentation) queries, the option to set "Min time interval" is not available.

Would it be possible to allow this also to be set with MetaQueries?

Thanks,
Andreas

**Comment by Gauravshah** [comment]
hello,
Went through the documentation here http://docs.grafana.org/features/datasources/mysql/#min-time-interval
it seems datasource specific option than a generic one. meta-queries by itself doesn't have any interval. Its the underneath query that has it. So if you are doing MetaQuery B on top of Influx Query A, It would work as long as Influx Min Time interval is set correctly.  That is of course given that influxdb data source supports that option

**Comment by TheRealKerni** [comment]
Hi,

correct it is data source specific. The problem is when I am choosing "MetaQueries" as a data source, I can't specify this for any "sub" InfluxDB datasources. Grafana only provides this at the top level data source or when using "Mixed" instead of MetaQueries at the top level.

But with the "Mixed" option it is not possible to use MetaQueries. Maybe there is a way to enable the same behaviour for this option as "Mixed" has.

Sorry, should have been more precise and investigated more before writing this.

Thanks,
Andreas

**Comment by Gauravshah** [comment]
can you point some example screenshot & documentation to it ? I did some search but failed to find examples

**Comment by TheRealKerni** [comment]
Absolutely, here is a screenshot with "Data Source" set to "--Mixed"-- showing the option for "Min time interval"

<img width="515" alt="screenshot" src="https://user-images.githubusercontent.com/42185/52556765-cfe68180-2ded-11e9-81dc-5332f2505e4b.png">

**Comment by Gauravshah** [comment]
thanks @TheRealKerni Makes sense. If you can test and open a PR it would be of great help. We are held up building backend plugin for sometime few weeks.

**Comment by TheRealKerni** [comment]
I'll give it a go :)

**Comment by TheRealKerni** [comment]
I guess we  can close this. Thank you!
