### ISSUE TITLE
Hide original metrics

### ISSUE THREAD

**Issue by dr1s** [GoshPosh/grafana-meta-queries#5]
Is there a way to hide the non computed metrics? 
e.g. I have 2 queries A and B and a arithmetical computed metric which is C=B-A.
Is there a way to only show C?

**Comment by Gauravshah** [comment]
that should be supported by original data source plugin using the eye icon. It works in case of druid.
<img width="1422" alt="screen shot 2017-11-30 at 9 35 29 pm" src="https://user-images.githubusercontent.com/620559/33469250-814ec58a-d616-11e7-9768-8333ff763b40.png">

**Comment by appunni-dishq** [comment]
Yes I was going through this, and I get the undefined error. I am trying to resolve this code. If I can I will surely send a pull request

**Comment by appunni-dishq** [comment]
By the way I am using Influxdb 0.9 plugin

**Comment by Gauravshah** [comment]
@dr1s @appunni-dishq  can you send in you trace from browser console, might have to do with the way we unhide it internally for querying

**Comment by appunni-dishq** [comment]
```
TypeError: Cannot read property 'returning' of undefined
    at eval (eval at <anonymous> (datasource.js?bust=1512114242641:NaN), <anonymous>:3:10)
    at eval (datasource.js?bust=1512114242641:229)
    at Array.forEach (<anonymous>)
    at eval (datasource.js?bust=1512114242641:225)
    at i (boot.e4836696.js:61)
    at boot.e4836696.js:61
    at o.$eval (boot.e4836696.js:61)
    at o.$digest (boot.e4836696.js:61)
    at o.$apply (boot.e4836696.js:61)
    at boot.e4836696.js:61
datasource.js?bust=1512114242641:232 TypeError: Cannot read property 'new' of undefined
    at eval (eval at <anonymous> (datasource.js?bust=1512114242641:NaN), <anonymous>:3:25)
    at eval (datasource.js?bust=1512114242641:229)
    at Array.forEach (<anonymous>)
    at eval (datasource.js?bust=1512114242641:225)
    at i (boot.e4836696.js:61)
    at boot.e4836696.js:61
    at o.$eval (boot.e4836696.js:61)
    at o.$digest (boot.e4836696.js:61)
    at o.$apply (boot.e4836696.js:61)
    at boot.e4836696.js:61
```
![image](https://user-images.githubusercontent.com/31534711/33472894-2a01b9fc-d69a-11e7-9c86-34133b473a6a.png)

**Comment by Gauravshah** [comment]
It should be `B['returning']/A['new']`

**Comment by appunni-dishq** [comment]
Same error

**Comment by appunni-dishq** [comment]
Observation: It works when I only use single Series, But the undefined error is there . Value is shown. But when I add another series value the whole thing becomes 0.

**Comment by appunni-dishq** [comment]
I figured my issue, I was using single Stat panel. 
{1511512636322: {new: 305} },{ 1511512636321: {returning: 28}} but resultHash was giving this as output, so it was forEaching either A or B so when function evaluates either A or B is non existent and result remains 0

**Comment by dr1s** [comment]
Here is my output from the webconsole.

<img width="1667" alt="metrics" src="https://user-images.githubusercontent.com/7274704/33475792-3fd40a10-d6b2-11e7-8da0-7aba62a53063.png">

[grafana-1512119091559.txt](https://github.com/GoshPosh/grafana-meta-queries/files/1520949/grafana-1512119091559.txt)

**Comment by Gauravshah** [comment]
@dr1s can you try now, added a fix

**Comment by Gauravshah** [comment]
closing as fixed in https://github.com/GoshPosh/grafana-meta-queries/commit/0edf79b22809f0d5da818eb77bbb87d61bec8fd9
