### ISSUE TITLE
Arithmetic calculation across difference datasource is not work ? 

### ISSUE THREAD

**Issue by kantsuw** [GoshPosh/grafana-meta-queries#50]
As test to calculate between elasticsearch to elasticsearch , influx to influx
This plugin work very well.

However , I try to calculate across between elasticsearch & influx
it not work.

Is there any example of calculation across datasource ?

**Comment by ShilpaSivanesan** [comment]
@kantsuw I have verified across redshift and druid data source. It works well
could you add screenshots of your example?

**Comment by kantsuw** [comment]
It my faluse, the alias in expression is not corrent.
