### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by johntdyer** [GoshPosh/grafana-meta-queries#53]
The released on grafana appears to bne 0.0.1
```
grafana-cli plugins install goshposh-metaqueries-datasource

```

it appears there is significant development since 2017 so I'd like to new a new release cut

**Comment by Gauravshah** [comment]
@ShilpaSivanesan

**Comment by Gauravshah** [comment]
released https://github.com/GoshPosh/grafana-meta-queries/releases/tag/0.0.2

**Comment by Gauravshah** [comment]
created a PR on plugin repo https://github.com/grafana/grafana-plugin-repository/pull/438
