### ISSUE TITLE
No output for Arithmetic and exception for TimeShift and MovingAverage

### ISSUE THREAD

**Issue by victr** [GoshPosh/grafana-meta-queries#54]
Hi
I've tried with the same settings as shown in the readme, but it doesn't work.
For Arithmetic there's no line on the graph
![image](https://user-images.githubusercontent.com/1419684/57297530-19cec300-70d0-11e9-8189-aa1df09c946c.png)
And for TimeShift and MovingAverage it fails with an exception:
```
Panel data error: TypeError: Cannot set property 'hide' of undefined
    at timeshift (datasource.js:229)
    at eval (datasource.js:105)
    at qt (lodash.js:516)
    at Function.Wa (lodash.js:9343)
    at MetaQueriesDatasource._doQuery (datasource.js:96)
    at eval (datasource.js:52)
    at lodash.js:4911
    at Vr (lodash.js:2996)
    at lodash.js:4880
    at Function.Wa (lodash.js:9343)
```

**Comment by Gauravshah** [comment]
your panel data source needs to be grafana, you have set it as Mixed
<img width="1532" alt="Screen Shot 2019-05-07 at 9 37 50 AM" src="https://user-images.githubusercontent.com/620559/57316987-e0845c00-70ab-11e9-9aa7-6a1002b3e0cc.png">

**Comment by victr** [comment]
Grafana ds equals random test data, at least with my grafana configuration. Afaiu mixed is the only way to combine two different datasources, and meta queries is a datasource.
![image](https://user-images.githubusercontent.com/1419684/57361259-5657f880-717c-11e9-883a-5765a1db44db.png)

**Comment by Gauravshah** [comment]
@victr can you try setting data source as "Meta queries" instead of "Grafana"

**Comment by victr** [comment]
I've moved on to a different plugin, but thanks for your help.

**Comment by Gauravshah** [comment]
@victr curious, what other plugin supports multiple metrics ?

**Comment by victr** [comment]
@Gauravshah mine does :) but no sliding window yet https://github.com/liquidm/grafana-mixtransform/

**Comment by Gauravshah** [comment]
cool, arithmetic does support what you are trying to rewrite
