### ISSUE TITLE
Add hiddenQueries: true to plugin.json for v6.2+ support with hidden queries 

### ISSUE THREAD

**Issue by torkelo** [GoshPosh/grafana-meta-queries#55]
Starting in v6.2 Grafana will filter out hidden queries before sending them to data sources as 90% of data sources do not need them and have to remember to filter them out themselves. 

But some data sources that have queries that can refer to other queries still need hidden queries. 

So add :
"hiddenQueries": true, 

to plugin json.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/pull/17124

**Comment by Gauravshah** [comment]
thanks @torkelo
