### ISSUE TITLE
Update plugins.json with new version

### ISSUE THREAD

**Issue by bmanth60** [GoshPosh/grafana-meta-queries#58]
I see that a new release of this plugin for 0.0.2 was created 6 days ago but I don't see the new version available on https://grafana.com/plugins/goshposh-metaqueries-datasource. Should the plugins.json also be updated with the version? https://github.com/GoshPosh/grafana-meta-queries/blob/master/src/plugin.json#L15

**Comment by Gauravshah** [comment]
thanks @bmanth60
