### ISSUE TITLE
Problem with ElasticSearch and Arithmetic

### ISSUE THREAD

**Issue by tiago-cruz-movile** [GoshPosh/grafana-meta-queries#60]
Hello,

I have this example, using Grafana 6.2 with ElasticSearch 5.6:

![image](https://user-images.githubusercontent.com/4048174/59699970-dc7a4c80-91c8-11e9-8a1b-514e2b946da3.png)

Values: 
- deliveredAt: `11:43:25`
- sentAt: `11:30:59`

![image](https://user-images.githubusercontent.com/4048174/59700122-18adad00-91c9-11e9-8b73-23a62f5bbaff.png)

- Using 'Date & Time' just to check vs 'None' unit:

![image](https://user-images.githubusercontent.com/4048174/59700212-47c41e80-91c9-11e9-9b4a-8d3464b59b87.png)

- Value of A: `1560869005000` (delivered)
- Value of B: `1560868259910` (sent)

Expression: `A['delivered']-B['sent']`

- A-B (expect): **`745090`**
- A-B (result): `8188`

**Comment by Gauravshah** [comment]
are you using single stats with `avg`. Its likely that it is dividing by 90 days of your date range.
<img width="424" alt="Screen Shot 2019-06-18 at 9 57 08 PM" src="https://user-images.githubusercontent.com/620559/59737874-1b81bf80-9214-11e9-8b3c-91458c350ab5.png">
<img width="509" alt="Screen Shot 2019-06-18 at 9 56 59 PM" src="https://user-images.githubusercontent.com/620559/59737877-1de41980-9214-11e9-9a08-32cd58bd0113.png">

**Comment by Gauravshah** [comment]
@tiago-cruz-movile can we close this ?
