### ISSUE TITLE
install fails in grafana official Docker image

### ISSUE THREAD

**Issue by alberanid** [GoshPosh/grafana-meta-queries#7]
Hi,
I'm unable to install the plugin work with the official Grafana Docker image (4.6.2).

The closer I got is creating a Dockerfile like this:

    FROM grafana/grafana
    ADD ./grafana-meta-queries/dist/* /usr/share/grafana/public/app/plugins/datasource/goshposh-metaqueries-datasource/

Then the *MetaQueries* type is shown, when I try to add a new data source, but when I select it I got this error:

    Plugin Error
    Fetch error: 404 Not Found Instantiating http://localhost:3000/public/app/plugins/datasource/goshposh-metaqueries-datasource/module Loading app/plugins/datasource/goshposh-metaqueries-datasource/module

I tried with master, 0.0.1 and rebuilding the dist files with grunt default.

I've nothing meaningful in the Grafana logs; on the browser, I can say that the call to /api/plugins/goshposh-metaqueries-datasource/settings returns correctly:

> {"name":"MetaQueries","type":"datasource","id":"goshposh-metaqueries-datasource","enabled":false,"pinned":false,"module":"app/plugins/datasource/goshposh-metaqueries-datasource/module","baseUrl":"public/app/plugins/datasource/goshposh-metaqueries-datasource","info":{"author":{"name":"Gaurav Shah","url":"https://github.com/GoshPosh/grafana-meta-queries"},"description":"","links":[{"name":"GitHub","url":"https://github.com/GoshPosh/grafana-meta-queries#readme"}],"logos":{"small":"public/app/plugins/datasource/goshposh-metaqueries-datasource/img/logo.png","large":"public/app/plugins/datasource/goshposh-metaqueries-datasource/img/logo.png"},"screenshots":null,"version":"0.0.1","updated":""},"includes":null,"dependencies":{"grafanaVersion":"*","plugins":[]},"jsonData":null,"defaultNavUrl":"","latestVersion":"","hasUpdate":false,"state":""}

On the console, I then got this:

    Plugin component error Error: Fetch error: 404 Not Found
      Instantiating http://localhost:3000/public/app/plugins/datasource/goshposh-metaqueries-datasource/module
      Loading app/plugins/datasource/goshposh-metaqueries-datasource/module
        at index.js:33
        at <anonymous>

Any idea on how to fix it?

Thanks!

**Comment by Gauravshah** [comment]
Did the following:
```
docker run -d -v /var/lib/grafana --name grafana-storage busybox:latest
docker run \
   -d \
   -p 3000:3000 \
   --name=grafana \
   --volumes-from grafana-storage \
   grafana/grafana
docker exec -it grafana /bin/bash
apt-get update
apt-get upgrade
apt-get install git
cd /var/lib/grafana/plugins
git clone https://github.com/GoshPosh/grafana-meta-queries.git
exit
docker restart grafana
docker exec -it grafana /bin/bash
cd /var/lib/grafana/plugins/grafana-meta-queries/
```
open localhost and add new datasource.

**Comment by alberanid** [comment]
@Gauravshah : thanks; the problem is that I need to start with the official image; I'll try to adapt your instructions to work with it.  Thanks!

**Comment by Gauravshah** [comment]
since the plugin is not published with grafana I do not know of a simpler way to do it.

**Comment by Gauravshah** [comment]
will have to wait for this one https://github.com/grafana/grafana-plugin-repository/pull/183

**Comment by alberanid** [comment]
thanks, I hope it's included soon, since it very useful!
