### ISSUE TITLE
MetaQuery breaks in latest version of Grafana

### ISSUE THREAD

**Issue by yuvarajhere** [GoshPosh/grafana-meta-queries#82]
From version 6.4.2, the metaquery plugin breaks and doesn't return any value. The reason might be the Grafana recent version is using a different data format and it breaks the plugin. 

I have tested with "Arithemetic" type and not sure about the other types. 

Error Message:
![Screen Shot 2019-10-17 at 10 08 15 AM](https://user-images.githubusercontent.com/29648850/67011483-17808400-f0c6-11e9-9193-3ced6659a460.png)

**Comment by codemoos** [comment]
Can confirm that something with metaqueries and grafana is not working as it used to. I use metaqueries to retrieve data from the source, but plotting in grafana returns undefined error.

**Comment by gailmichi** [comment]
Same problem here. I don't even get an error message. My browser hangs up if i try to use metaqueries. (Grafana 6.4.3 on Ubuntu Server)

**Comment by bhozar** [comment]
Grafana 6.5.0-beta1 is showing similar behavior. I receive an error message when using it with multiple Azure Application Insight data sources which were previously working in 6.4.x

Each query and panel displays:

**Metric request error**

**Comment by Gauravshah** [comment]
@tonymadbrain It should generally work with any datasource , can you help with 1 metric and 1 meta query on top of just trying to print the same value ?

**Comment by Gauravshah** [comment]
@bhozar can you add stack trace and dashboard config ?

**Comment by bhozar** [comment]
![image](https://user-images.githubusercontent.com/1184220/69069008-abbf6d00-0a1d-11ea-80d7-e86b92a3bb63.png)

^ You mean this bit of the config? Where can I find the stack trace?

**Comment by bhozar** [comment]
Found it:

`error="{\"error\":{\"message\":\"The request had some invalid properties\",\"code\":\"BadArgumentError\",\"details\":[{\"code\":\"BadArgumentError\",\"target\":\"granularity\",\"message\":\"Failed parsing 'PTPTMM' as ISO8601 duration\"}],\"innererror\":{\"code\":\"QueryValidationError\",\"message\":\"Failed parsing the query\"}}}"`

Looks like it works if I set the time grain to something else:
![image](https://user-images.githubusercontent.com/1184220/69071346-a532f480-0a21-11ea-9174-be10d7bed5fa.png)

**Comment by Gauravshah** [comment]
@bhozar thats the error, can you send trace. It should be part of browser console

**Comment by bhozar** [comment]
Unfortunately I cannot replicate it now. Changing the Time Grain and changing it back seems to have fixed it. If it happens again I'll grab the browser console trace.

**Comment by siegmund42** [comment]
For me there isn't even an error. It does not even display any data when selecting metaQueries data source ("No data"). Selecting prometheus data source in the panel works fine for the shown query. Browser console looks clean.
![grafik](https://user-images.githubusercontent.com/9254869/69283884-9731cf00-0bed-11ea-9a0c-2bc86e1ed101.png)

Query inspector returns valid data:
```Object
  xhrStatus:"complete"
  request:Object
    method:"GET"
    url:"api/datasources/proxy/1/api/v1/query_range?query=up&start=1574116920&end=1574289720&step=120"
  response:Object
    status:"success"
    data:Object
      resultType:"matrix"
      result:Array[8]
```

Any idea how to debug this?

Grafana v6.4.4 (commit: 092e514)
Promethes version: 2.14.0

**Comment by tonymadbrain** [comment]
> @tonymadbrain It should generally work with any datasource , can you help with 1 metric and 1 meta query on top of just trying to print the same value ?

my metric:
![Screenshot 2019-12-05 at 13 19 12](https://user-images.githubusercontent.com/5266592/70226769-7c6d6780-1762-11ea-9e5d-4a9f5063c4bc.png)

when added metaquery with timeshift by default:
![Screenshot 2019-12-05 at 13 19 55](https://user-images.githubusercontent.com/5266592/70226846-9a3acc80-1762-11ea-9233-d437fe7a4e1f.png)

when changed timeshift to arithmetic, just no data:
![Screenshot 2019-12-05 at 13 20 58](https://user-images.githubusercontent.com/5266592/70226887-afaff680-1762-11ea-90cd-2253f06c0e9f.png)

**Comment by Gauravshah** [comment]
@tonymadbrain `Query  -- MIXED --` is incorrect. It should be  `Query  -- Meta Queries --`

**Comment by tonymadbrain** [comment]
> @tonymadbrain `Query -- MIXED --` is incorrect. It should be `Query -- Meta Queries --`

If I choose Meta Queries there is no data at all:
![Screenshot 2019-12-07 at 21 13 51](https://user-images.githubusercontent.com/5266592/70378867-b000eb00-1936-11ea-9587-39b64ef194ad.png)

Also no errors in console

**Comment by Gauravshah** [comment]
@tonymadbrain I am unsure why prometheus would not work

**Comment by siegmund42** [comment]
@Gauravshah Can we somehow support debugging this? Although #84 is now fixed, this still makes MetaQuery unusable for prometheus users.

**Comment by Gauravshah** [comment]
@tonymadbrain @siegmund42 I can take a look at prometheus after 2 weeks.  I do not know Prometheus so if you can add a link that can give prometheus test machine with sample data that would be helpful.

**Comment by siegmund42** [comment]
You might use this Prometheus demo server as data source: http://demo.robustperception.io:9090/graph?g0.range_input=1h&g0.expr=up&g0.tab=1

**Comment by siegmund42** [comment]
@Gauravshah You might want to use this Prometheus demo server as data source (I already a _very_ basic query to the URL): http://demo.robustperception.io:9090/graph?g0.range_input=1h&g0.expr=up&g0.tab=1

**Comment by siegmund42** [comment]
Any news on this? I just took a quick look in the javascript console and it gives:
`TypeError: this.props.panelData is undefined PromLink.tsx:23:19`

Anyway, request and response data look good so it's just a matter of presentation I guess.

**Comment by Gauravshah** [comment]
@siegmund42 moved the conversation here https://github.com/GoshPosh/grafana-meta-queries/issues/94
