### ISSUE TITLE
Unable to add MetaQueries Query since Grafana 6.5

### ISSUE THREAD

**Issue by TheRealKerni** [GoshPosh/grafana-meta-queries#84]
Starting with Grafana 6.5.0 I can't seem to add a new query of type "MetaQueries" any longer. The datatype of the panel is set to "MetaQueries". I have the latest version 0.0.3 of MetaQueries installed.
 
<img width="645" alt="Screenshot 2019-11-29 at 14 02 01" src="https://user-images.githubusercontent.com/42185/69870776-4424df80-12b1-11ea-9f6a-7aaa6635af54.png">

Does anyone have an idea why this is happening?

**Comment by Gauravshah** [comment]
Looks like grafana issue, reported it here :
https://github.com/grafana/grafana/issues/20793

Seems they no longer show mixed queries on the `Queries` tab

**Comment by qyvlik** [comment]
@Gauravshah which version of grafana can work meta-queries?

**Comment by Gauravshah** [comment]
@qyvlik 6.3 works. I am not sure for 6.4
6.5 doesn't work

**Comment by qyvlik** [comment]
@Gauravshah 
I use `Grafana v6.6.0-pre (e9f9912dea)`, it very new.
I try rollback grafana version to `6.3.0`.

**Comment by TheRealKerni** [comment]
Grafana 6.5.2 fixes this. Thanks @Gauravshah !
