### ISSUE TITLE
Can't use queries in arithmetics

### ISSUE THREAD

**Issue by Watermeloune** [GoshPosh/grafana-meta-queries#88]
Hello, I'm trying to use MetaQueries's datasource to do simple arithmetic with my queries but I really don't understand why it is not working

![metaqueriesfail](https://user-images.githubusercontent.com/15726170/72885397-2059a500-3d08-11ea-849f-9b59911105fe.png)

I followed examples given in several issues and it seems that you just have to write:
 **Query's name** + **other query's name**

still I don't have any value.

EDIT: I'm using grafana 6.5.3

**Comment by Gauravshah** [comment]
Please go through the Readme before opening an issue.

https://raw.githubusercontent.com/GoshPosh/grafana-meta-queries/master/img/arithmetic-ex1.png?raw=true

says `A['something']`

**Comment by Watermeloune** [comment]
Hi, sorry I had also try this way but I didn't think about putting metaqueries datasource in the end, my bad. Anyway, thanks

**Comment by Gauravshah** [comment]
glad it worked out for you @Watermeloune
