### ISSUE TITLE
Difference Memory with MetaQueries 

### ISSUE THREAD

**Issue by Claudiocre** [GoshPosh/grafana-meta-queries#90]
Hi all, sorry for my spupid ask, but I am new in this world. 
Moreover I have simil problem of[ this iussue](https://github.com/GoshPosh/grafana-meta-queries/issues/34)  .  I want see the difference of the memory used  from two query with the plugin zabbix. indeed I have implemented two query, one with the Total Memory and  the second con Free Memory. in the  third query (MetaQuery) I want see the difference.
How I can resolve this problem? 
![Grafana MetaQueries](https://user-images.githubusercontent.com/60424485/73341792-a1231e80-427d-11ea-9661-f521b5128c11.JPG)

**Comment by Gauravshah** [comment]
panel data source should not be `Mixed` It should be metaqueries

**Comment by Claudiocre** [comment]
I have change the DataSource and now it's visible, sorry for the my naivety
