### ISSUE TITLE
Metaqueries works incorrect with metrics from Zabbix datasource

### ISSUE THREAD

**Issue by SergeyRim** [GoshPosh/grafana-meta-queries#92]
Hello.
I have a Grafana v6.6.1 with Zabbix plugin.

For example I have added 2 metrics from zabbix datasource: "Number of packets received on interface Network adapter 1" for 2 different hosts (metric A and metric B).
Then I added an arithmetic metaqueries metric. 
The behaivor is:
No matter if I put A['Number of packets received on interface Network adapter 1'] or B['Number of packets received on interface Network adapter 1'] to the expression, it always show me a A['Number of packets received on interface Network adapter 1'] value.
![Screenshot_2](https://user-images.githubusercontent.com/30080321/75015557-ec55d900-5499-11ea-9781-20d69aa819a5.png)

If I change an expression to A['Number of packets received on interface Network adapter 1']+B['Number of packets received on interface Network adapter 1'], it will calculate B+B.
![Screenshot_3](https://user-images.githubusercontent.com/30080321/75016183-73f01780-549b-11ea-8490-d3b38ca44a10.png)

I have verified with a different metrics and expressions, and always metaqueries metric shows an incorrect result ( and sometime just shows an empty value without any errors displayed).

**Comment by vicioussn** [comment]
Same issue for me

**Comment by Gauravshah** [comment]
@vicioussn did you try debugging?

**Comment by apoorva-marisomaradhya** [comment]
@Gauravshah Hey, does this plugin work with grafana v6.7 and above? I am trying to get this work with v6.7.1 and MetaQuery plugin doesn't endup showing any data.

**Comment by Gauravshah** [comment]
@apoorva-marisomaradhya can you open a separate issue we can discuss there. also do paste a screenshot of your dashboard config

**Comment by SergeyRim** [comment]
Sorry for late response. Not sure how to do a debugging with console.log, but my issue is very easy to reproduce.
![Screenshot_4](https://user-images.githubusercontent.com/30080321/78221995-1359ee80-74cd-11ea-942c-8c3ca0a31093.png)

**Comment by SergeyRim** [comment]
Debugging shows that calculation is correct, but the graph looks very ugly. So the issue is in the graph itself?
![Screenshot_5](https://user-images.githubusercontent.com/30080321/78228189-0e01a180-74d7-11ea-8549-742aeb0a8dc9.png)

**Comment by Gauravshah** [comment]
so we are one step forward now. You can convert your graph to table . That will help understand data better. Looks to me that there is a null on either A or B and non-null on the other side hence the sum is throwing as NAN. Once you confirm it via table you can write some javascript safety check. ` (A['number_of....'].isNaN()? 0 : A['number_of....']` something like that should take care of exceptions in data

**Comment by SergeyRim** [comment]
I have converted graph to table and now can see the issue. Data for A and B has different timestamps.
So how to use MetaQueries in this case?
![Screenshot_6](https://user-images.githubusercontent.com/30080321/78240428-aef85880-74e7-11ea-81f1-26808d72954f.png)

**Comment by Gauravshah** [comment]
you might want to  set some granularity on your A source so that it is grouped by the same time as the other one. I do not know how otherwise can Metaqueries do the summation.

**Comment by SergeyRim** [comment]
This is how zabbix collects data. The previous screenshot was from esxi stats collected by zabbix, here is a snmp stats collected from router by zabbix. The main problem is the same - different timestamps. I'm really not sure that I can influence on this.
![Screenshot_7](https://user-images.githubusercontent.com/30080321/78245382-0c90a300-74f0-11ea-8a8f-e94e3d628cf4.png)

**Comment by Gauravshah** [comment]
@SergeyRim I am not sure how to do that on zabbix, but unless we get the time granularity to be similar across columns there is no way metaqueries will be able to apply any operation

**Comment by Gauravshah** [comment]
closing this one as its not related to metaqueries
