### ISSUE TITLE
Question: Meta Queries with JSON Datasource

### ISSUE THREAD

**Issue by kghogue2** [GoshPosh/grafana-meta-queries#93]
I am using SIMPOD-JSON-DATASOURCE, and I am trying to apply meta queries for arithmetic operations not offered by the JSON datasource. 

I am running into issues with how to refer to my query, and I am not finding much information. I am also probably running into issues with null data, as my data source has significant latency (>3 min)

![image](https://user-images.githubusercontent.com/37410379/75819427-aa197b00-5d68-11ea-94a5-6cb3e151b53e.png)

**Comment by Gauravshah** [comment]
A['Jones Street.....750 W'] needs to be put in.  I am not sure how SIMPOD works but in general what is being shown on graph can be used as name

**Comment by kghogue2** [comment]
That worked perfectly! Thank you so much for the quick response!
