### ISSUE TITLE
Does the plugin work with grafana v6.7 and above??

### ISSUE THREAD

**Issue by apoorva-marisomaradhya** [GoshPosh/grafana-meta-queries#95]
Hi!!

I deployed the plugin on our grafana v6.7.1 and tested out with cloudwatch & prometheus datasource, tests didn't not give any result. Any help would be appreciated.  

Have attached the screenshot of dashboard I was working on.

![image](https://user-images.githubusercontent.com/45768960/78000135-6c047c80-7351-11ea-97ec-0dd3164da270.png)

**Comment by Gauravshah** [comment]
Prometheus does have issues and we have not spent time on it. Cloudwatch does work. Looking at the panel I don't find anything aboivious.

can you try console.log(A) in the B's expression and then verify on console what does it print.

**Comment by Gauravshah** [comment]
looks like there are breaking changes https://github.com/grafana/grafana/releases/tag/v6.7.0-beta1. We have not tested it on 6.7. The latest we have tested is 6.5.2

**Comment by apoorva-marisomaradhya** [comment]
Tried console.log(A), still no data.

**Comment by Gauravshah** [comment]
that would print in web browser's console

**Comment by benjaminsaurusrex** [comment]
@Gauravshah - are there any plans to make this work with `6.7+`? I've also tested numerous flavors of `console` logging to no avail. Would love to use this if possible.

**Comment by Gauravshah** [comment]
@benjaminsaurusrex we wouldn't be able to get to it in next 4-6 weeks. we should be able to look after that.

**Comment by Gauravshah** [comment]
tested works on grafana 7.0.3
