### ISSUE TITLE
Question: Substracting Dates

### ISSUE THREAD

**Issue by NightDragon1** [GoshPosh/grafana-meta-queries#99]
Hi,

Is there a way to substract a date from a date field? e.g. -1d or so?

Thx,
BR,

Rob

**Comment by Gauravshah** [comment]
you should be able to write javascript 

 new Date(A['some_col']).setDate(( new Date(A['some_col']))-5);

**Comment by NightDragon1** [comment]
Hi!

Thanks for your answer. I solved it by adjusting the database and adding a view with date -1d.

BR,
Rob
